exp1:
  clean_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/train
  save_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/Synthesized_1/test
  degradations:
    -
      type: RandomBlur
      bins: 1
      kernel_size: 3
      sigma_range: [0, 1]
    -
      type: RandomResize
      bins: 1
      scale_range: [0.25, 0.25]
      interpolation: bicubic
    -
      type: RandomNoise
      bins: 1
      noise_range: [0, 10]
      is_gray_noise: true
    -
      type: RandomJPEGCompression
      bins: 1
      quality_range: [80, 90]
      color_type: color

exp2:
  clean_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/train
  save_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/Synthesized_2/test
  degradations:
    -
      type: RandomBlur
      bins: 1
      kernel_size: 3
      sigma_range: [0.5, 1.5]
    -
      type: RandomResize
      bins: 1
      scale_range: [0.25, 0.25]
      interpolation: bicubic
    -
      type: RandomNoise
      bins: 1
      noise_range: [15, 25]
      is_gray_noise: true
    -
      type: RandomJPEGCompression
      bins: 1
      quality_range: [75, 85]
      color_type: color

exp3:
  clean_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/train
  save_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/Synthesized_3/test
  degradations:
    -
      type: RandomBlur
      bins: 1
      kernel_size: 3
      sigma_range: [1.5, 2.5]
    -
      type: RandomResize
      bins: 1
      scale_range: [0.25, 0.25]
      interpolation: bicubic
    -
      type: RandomNoise
      bins: 1
      noise_range: [5, 15]
      is_gray_noise: true
    -
      type: RandomJPEGCompression
      bins: 1
      quality_range: [75, 85]
      color_type: color

exp4:
  clean_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/train
  save_path: /nas/k8s/dev/research/intern/jhmin/test_project/despeckle/CTD/PIPAL/Synthesized_4/test
  degradations:
    -
      type: RandomBlur
      bins: 1
      kernel_size: 3
      sigma_range: [2.5, 3.5]
    -
      type: RandomResize
      bins: 1
      scale_range: [0.25, 0.25]
      interpolation: bicubic
    -
      type: RandomNoise
      bins: 1
      noise_range: [25, 35]
      is_gray_noise: true
    -
      type: RandomJPEGCompression
      bins: 1
      quality_range: [65, 75]
      color_type: color
