metric:
  type: FrechetDistanceSoftmax
  model:
    type: AlexNetImageNet

model:
  type: AlexNetImageNet
# bin setting 해놓음. 5,5,3
degradations:
  -
    type: RandomBlur
    bins: 5
    kernel_size: 11
    sigma_range: [0, 5]
  -
      type: RandomResize
      bins: 1
      arb_size:
      scale_range: [0.25, 0.25]
      interpolation: bicubic
  -
    type: RandomNoise
    bins: 5
    noise_range: [0, 50]
    is_gray_noise: true
  -
    type: RandomJPEGCompression
    bins: [[30, 50], [50, 70], [70, 90]]
    quality_range: [30, 90]
    color_type: color
    
# tgt_path : lr , src_path : hr
dataset:
  tgt_path: /nas/k8s/dev/research/intern/jhmin/test_project/Datasets/PIPAL/CTD/test/setting1/LR/
  src_path: /nas/k8s/dev/research/intern/jhmin/test_project/Datasets/PIPAL/CTD/train/
  degradations:
    -
      type: RandomBlur
      bins: 1
      kernel_size: 11
      sigma_range: [0, 1]
    -
      type: RandomResize
      bins: 1
      arb_size:
      scale_range: [0.25, 0.25]
      interpolation: bicubic
    -
      type: RandomNoise
      bins: 1
      noise_range: [0, 10]
      is_gray_noise: true
    -
      type: RandomJPEGCompression
      bins: 1
      quality_range: [80, 90]
      color_type: color
